extern const GeoLayout green_spring_geo[];
extern Vtx green_spring_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx green_spring_Cube_mesh_layer_1_vtx_0[96];
extern Gfx green_spring_Cube_mesh_layer_1_tri_0[];
extern Vtx green_spring_Cube_mesh_layer_1_vtx_1[28];
extern Gfx green_spring_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_green_spring_f3d_material[];
extern Gfx mat_green_spring_f3d_material_001[];
extern Gfx green_spring_Cube_mesh_layer_1[];
extern Gfx green_spring_material_revert_render_settings[];
