#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -156, -6585, 8735, castle_grounds_dl_A_TopGround_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, castle_grounds_dl_A_TopGround_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_B_MiddleGround_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_B_Path_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -156, -6585, 8735, castle_grounds_dl_B_Rock2Visual_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -156, -6585, 8735, castle_grounds_dl_B_RockVisual_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_C_LowGround_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_D_GroundPlaza2_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_E_Beach_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_E_GroundPlaza_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, castle_grounds_dl_E_GroundPlaza_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -5902, -6535, 8815),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -7, -579, 9),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(4000, 32000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_LanternLOD_mesh_layer_4),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_LanternLOD_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -9, -568, 9),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-2048, 4000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_LanternVisual_mesh_layer_1),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_LanternVisual_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -5911, -6535, 11225),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -7, -579, 9),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(4000, 32000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_LanternLOD_001_mesh_layer_4),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_LanternLOD_001_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -9, -568, 9),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-2048, 4000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_LanternVisual_001_mesh_layer_1),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_LanternVisual_001_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4875, -5143, 5303),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 11, -859, 65),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(2500, 32000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_MagazineStandLOD_001_mesh_layer_1),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_MagazineStandLOD_001_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 11, -859, 65),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-2048, 2500),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_MagazineStandVisual_001_mesh_layer_1),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_MagazineStandVisual_001_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1298, -5143, 5303),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -6, -859, 65),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(2500, 32000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_MagazineStandLOD_mesh_layer_1),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_MagazineStandLOD_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -6, -859, 65),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-2048, 2500),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_MagazineStandVisual_mesh_layer_1),
					GEO_DISPLAY_LIST(4, castle_grounds_dl_MagazineStandVisual_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -266, -5326, 9160),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 17, -2043, -26),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-2048, 3000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_A_MusicNoteStatueVisual_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 17, -2043, -26),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(3000, 6000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_MusicNoteStatueVisualLOD1_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 17, -2043, -26),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(6000, 32000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, castle_grounds_dl_Z_MusicNoteStatueVisualLOD2_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3099, -7581, 9879, castle_grounds_dl_Palm_tree_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3099, -7581, 10375, castle_grounds_dl_Palm_tree_001_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3099, -7581, 10947, castle_grounds_dl_Palm_tree_002_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3099, -7581, 8450, castle_grounds_dl_Palm_tree_003_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3099, -7581, 7983, castle_grounds_dl_Palm_tree_004_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3099, -7581, 7573, castle_grounds_dl_Palm_tree_005_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, 776, -6218, 6439, castle_grounds_dl_PottedPlant_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, 788, -6222, 5327, castle_grounds_dl_PottedPlant_001_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, 1482, -3931, 3274, castle_grounds_dl_PottedPlant_002_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3555, -7219, 9613, castle_grounds_dl_PottedPlant_003_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3555, -7219, 8627, castle_grounds_dl_PottedPlant_004_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(4, -3697, -3931, 3855, castle_grounds_dl_PottedPlant_005_mesh_layer_4),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4230, -6850, 6971),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 5000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_StairsVisual_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4230, -6850, 6971),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(5000, 32000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_StairsVisualLOD_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1354, -8925, 13519, castle_grounds_dl_Towel_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1814, -9083, 14237, castle_grounds_dl_Towel_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 763, -8925, 13519, castle_grounds_dl_Towel_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 1560, -9083, 14237, castle_grounds_dl_Towel_003_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1413, -8233, 13183),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS_AND_DL(1, -9, -378, 13, castle_grounds_dl_UmbrellaPole_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, -10, -183, 13, castle_grounds_dl_UmbrellaTop_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1993, -8381, 13868),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS_AND_DL(1, -9, -378, 13, castle_grounds_dl_UmbrellaPole_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, -10, -183, 13, castle_grounds_dl_UmbrellaTop_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 643, -8179, 12941),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS_AND_DL(1, -9, -378, 13, castle_grounds_dl_UmbrellaPole_002_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, -10, -183, 13, castle_grounds_dl_UmbrellaTop_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1365, -8436, 14012),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS_AND_DL(1, -9, -378, 13, castle_grounds_dl_UmbrellaPole_003_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, -10, -183, 13, castle_grounds_dl_UmbrellaTop_003_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -379, -7808, 9126),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 3000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, castle_grounds_dl_WaterFountain_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -379, -7808, 9126),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(3000, 32000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, castle_grounds_dl_WaterFountainLOD_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 4320, -3422, 6017, castle_grounds_dl_Windows_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, castle_grounds_dl_Windows_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_Z_Exit_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, castle_grounds_dl_Z_Exit_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_Z_Exit_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_Z_Houses_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, castle_grounds_dl_Z_Houses_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_Z_Wall_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1604, -7985, 10605, castle_grounds_dl_Z_WallVisual_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -9289, 0, castle_grounds_dl_Z_Water_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, castle_grounds_dl_Z_Water_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(5, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, castle_grounds_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
