extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_ZELDA_MAJORA_S_MASK_B2A159AE_2_0_3D7E6E66_ciByRGBA_ci4[];
extern u8 bob_dl_ZELDA_MAJORA_S_MASK_B2A159AE_2_0_3D7E6E66_ciByRGBA_ci4_pal_rgba16[];
extern u8 bob_dl_B200_r10_Uroko_64x64_ci4_ci4[];
extern u8 bob_dl_B200_r10_Uroko_64x64_ci4_ci4_pal_rgba16[];
extern u8 bob_dl_cobblestone_floor_yellow_ci4[];
extern u8 bob_dl_cobblestone_floor_yellow_ci4_pal_rgba16[];
extern u8 bob_dl_DarkGrassMM2_rgba16[];
extern u8 bob_dl_DarkGrassMM1_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[58];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[6];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[13];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[295];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_4[5];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_4[];
extern Gfx mat_bob_dl_Yellow_wall[];
extern Gfx mat_revert_bob_dl_Yellow_wall[];
extern Gfx mat_bob_dl_Roof[];
extern Gfx mat_revert_bob_dl_Roof[];
extern Gfx mat_bob_dl_cobblestone_floor_yellow_001[];
extern Gfx mat_revert_bob_dl_cobblestone_floor_yellow_001[];
extern Gfx mat_bob_dl_multitexture_grass_layer1[];
extern Gfx mat_revert_bob_dl_multitexture_grass_layer1[];
extern Gfx mat_bob_dl_solid_pastel[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
