extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_DarkGrassMM2_rgba16[];
extern u8 bob_dl_DarkGrassMM1_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_multitexture_grass_layer1[];
extern Gfx mat_revert_bob_dl_multitexture_grass_layer1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
