extern const GeoLayout wood_platform_geo[];
extern u8 wood_platform_Bark04_64x64_ci4_ci4[];
extern u8 wood_platform_Bark04_64x64_ci4_ci4_pal_rgba16[];
extern u8 wood_platform_SlopeWood2_64x64_mirrored_ci4_ci4[];
extern u8 wood_platform_SlopeWood2_64x64_mirrored_ci4_ci4_pal_rgba16[];
extern Vtx wood_platform_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wood_platform_Cube_mesh_layer_1_vtx_0[16];
extern Gfx wood_platform_Cube_mesh_layer_1_tri_0[];
extern Vtx wood_platform_Cube_mesh_layer_1_vtx_1[8];
extern Gfx wood_platform_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_wood_platform_sides[];
extern Gfx mat_revert_wood_platform_sides[];
extern Gfx mat_wood_platform_top[];
extern Gfx mat_revert_wood_platform_top[];
extern Gfx wood_platform_Cube_mesh_layer_1[];
extern Gfx wood_platform_material_revert_render_settings[];
