#include "src/game/envfx_snow.h"

const GeoLayout bob_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bob_dl_1Room_geo),
			GEO_BRANCH(1, bob_dl_2Room_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -6174, 434, 5661),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_dl_1Room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -6438, 434, 5661),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -5644, -1567, 597),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, bob_dl_A_mainRoomVisual_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 3728, -3589, 2409),
			GEO_OPEN_NODE(),
				GEO_RENDER_RANGE(-5000, 10000),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, bob_dl_Backtrack_mesh_layer_1),
					GEO_DISPLAY_LIST(6, bob_dl_Backtrack_mesh_layer_6),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -9346, 1961, 4216),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, bob_dl_FakeRoom2_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1058, -3700, 3718, bob_dl_Z_Background_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_dl_2Room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -6784, 434, 5661),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -5297, -1567, 597),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, bob_dl_FakeRoom1_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -8999, 1961, 4216),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_update_fog),
				GEO_DISPLAY_LIST(1, bob_dl_room2_003_mesh_layer_1),
				GEO_DISPLAY_LIST(5, bob_dl_room2_003_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0xEF7B),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, -200000, 0, -100, -200000, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_BLIZZARD, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(5, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
