#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bob_dl_room1_geo),
			GEO_BRANCH(1, bob_dl_room2_001_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1355, 4596, 19494),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_dl_room1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1355, 4596, 19494),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 9170, -10151, -1217, bob_dl_A_Platform_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 11942, -10343, -3763, bob_dl_B_MountainAreaVisual_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, bob_dl_B_MountainAreaVisual_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 711, -11764, 5243, bob_dl_fakeRoom2_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, bob_dl_fakeRoom2_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1186, -11660, -692, bob_dl_mainRoom_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, bob_dl_mainRoom_mesh_layer_5),
				GEO_DISPLAY_LIST(6, bob_dl_mainRoom_mesh_layer_6),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 8145, -11907, -3490, bob_dl_Rocks_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 10078, -11310, -3490, bob_dl_Rocks_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 7567, -11470, -2081, bob_dl_TallRockVisual_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 10837, -10566, -2070, bob_dl_TallRockVisual_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 14311, -9565, -5410, bob_dl_TallRockVisual_002_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 8208, -8032, -6810, bob_dl_Z_Mountain_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_dl_room2_001_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1355, 4596, 19494),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 711, -11764, 5243, bob_dl_fakeRoom1_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, bob_dl_fakeRoom1_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(5, 10186, -7652, -9228, bob_dl_Lake_mesh_layer_5),
			GEO_TRANSLATE_NODE_WITH_DL(1, 12240, -8861, -8642, bob_dl_room2_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, bob_dl_room2_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(5, 11233, -8312, -8954, bob_dl_Waterfall_mesh_layer_5),
			GEO_TRANSLATE_NODE_WITH_DL(1, 8208, -8032, -6810, bob_dl_Z_Mountain_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(5, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
